// Design reference for the DXX Viewer FLTK GUI.
//
// The real app is hand-coded in fltk/ (FltkMainWindow.cpp etc.); this .fl
// mirrors its top-level layout so it can be opened/edited in Fluid.
//
// The three content panes are custom widgets (FltkTreePanel, FltkPropertiesPanel,
// FltkGeometryWidget) represented here as placeholders carrying only their class
// name. Their internals, Cairo drawing and callbacks are not representable in
// Fluid. The real layout uses a Fl_Tile anchored at (0,0) with a floating
// toolbar; here the toolbar is a separate strip above the tile for clarity.
// generated by Fast Light User Interface Designer (fluid) version 1.0405

#include "dxxviewer.h"

Fl_Flex *toolbar=(Fl_Flex *)0;

Fl_Tile *content=(Fl_Tile *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1180, 700, "DXX Viewer");
    w = o; (void)w;
    { toolbar = new Fl_Flex(0, 0, 1180, 32, "toolbar");
      toolbar->type(1);
      { new Fl_Button(0, 0, 169, 32, "Open");
      } // Fl_Button* o
      { new Fl_Button(169, 0, 169, 32, "Reload");
      } // Fl_Button* o
      { new Fl_Button(338, 0, 169, 32, "+ Expand");
      } // Fl_Button* o
      { new Fl_Button(507, 0, 169, 32, "- Collapse");
      } // Fl_Button* o
      { new Fl_Input(676, 0, 168, 32);
      } // Fl_Input* o
      { new Fl_Button(844, 0, 168, 32, "Find");
      } // Fl_Button* o
      { new Fl_Button(1012, 0, 168, 32, "X");
      } // Fl_Button* o
      toolbar->end();
    } // Fl_Flex* toolbar
    { content = new Fl_Tile(0, 32, 1180, 668, "content");
      content->end();
      Fl_Group::current()->resizable(content);
    } // Fl_Tile* content
    o->end();
  } // Fl_Double_Window* o
  return w;
}
