// generated by Fast Light User Interface Designer (fluid) version 1.0405

#ifndef dxxviewer_h
#define dxxviewer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Flex.H>
#include <FL/Fl_Tile.H>
#include "FltkTreePanel.h"
#include "FltkPropertiesPanel.h"
#include "FltkGeometryWidget.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Flex.H>
extern Fl_Flex *toolbar;
#include <FL/Fl_Button.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Tile.H>
extern Fl_Tile *content;
Fl_Double_Window* make_window();
#endif
